-- 코드를 입력하세요
# SELECT CAR_ID, ROUND(DATEDIFF(END_DATE, START_DATE), 2) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATEDIFF(END_DATE, START_DATE) >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE, START_DATE) + 1) / COUNT(CAR_ID), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7.0
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

# SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID ASC, DATEDIFF(END_DATE, START_DATE) DESC;